type_prefix MyPrefix;

import "my.idl";

static interface Navigation {
    optional Navigation 
}

// Doc @internal
weak_ref interface MyInterface (dart: myname) {
    /*
    Multiline doc @internal with tag @undocumented.
    */
    listener InternalListener {
        void onEvent<dart: onEventDart, cpp: onEventNative>(int param, int secondParam);
    }

    vector<int> val;
    int parameter;
    bitmap image readonly;
    void method(const string str);
}

lite struct MyStruct based on "file.proto":MyStruct {
    enum Orientation {
        // Left orientation
        Left,
        // Right orientation
        Right
    }

    // Orientation
    MyStruct.Orientation orientation = Orientation.Right;

    // doc
    string key based on key;
}
